# Nome del processo automatico, lo vedrai nella scheda "Actions" di GitHub
name: Deploy to GitHub Pages

# Trigger: fa partire il processo ogni volta che carichi ("push") nuovo codice
# sul branch "main"
on:
  push:
    branches: [ "main" ]

# Permessi: concede all'azione i permessi per scrivere sulla pagina di GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Lavori: definisce la sequenza di operazioni da eseguire
jobs:
  deploy:
    runs-on: ubuntu-latest # Usa un server virtuale con Ubuntu
    steps:
      # 1. Scarica il codice dal tuo repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Installa Node.js (versione 18)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      # 3. Installa tutte le dipendenze del progetto
      - name: Install dependencies
        run: npm install

      # 4. Compila il progetto per la produzione
      - name: Build project
        run: npm run build

      # 5. Configura GitHub Pages per accettare i file
      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5

      # 6. Carica i file compilati (dalla cartella 'dist')
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'
          
      # 7. Pubblica il sito
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
